// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import "./style.css";

// import Navbar from "./Navbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
       
//         {children}
       
//       </body>
//     </html>
//   );
// }


// layout.tsx
'use client';
import React from 'react';
 import "./globals.css";
 import "./style.css";
import { ThemeProvider, createTheme, CssBaseline } from '@mui/material';
import { useDarkModeStore } from './store'; // Adjust the import path as needed
import Navbar from './Navbar'; // Adjust the import path as needed

export default function Layout({ children }: { children: React.ReactNode }) {
 
  const { darkMode } = useDarkModeStore();

  const theme = createTheme({
    palette: {
      mode: darkMode ? 'dark' : 'light',
      primary: {
        main: darkMode ? '#90caf9' : '#1976d2',
      },
    },
  });

  return (
    <html>
      <body>
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Navbar />
      {children}
    </ThemeProvider>
    </body>
    </html>
  );
}
